"""baseline_initial_schema

Revision ID: 3cc081d1fee7
Revises: 
Create Date: 2025-11-27 13:11:36.308681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc081d1fee7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('value_ru', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionaries_category'), 'dictionaries', ['category'], unique=False)
    op.create_index(op.f('ix_dictionaries_id'), 'dictionaries', ['id'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('clinical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=100), nullable=True),
    sa.Column('date_filled', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('comorbidities', sa.JSON(), nullable=True),
    sa.Column('smoking_status', sa.String(length=50), nullable=True),
    sa.Column('comorbidities_other_text', sa.Text(), nullable=True),
    sa.Column('initial_diagnosis_date', sa.DateTime(), nullable=True),
    sa.Column('tnm_stage', sa.String(length=50), nullable=True),
    sa.Column('metastatic_disease_date', sa.DateTime(), nullable=True),
    sa.Column('histology', sa.String(length=100), nullable=True),
    sa.Column('alk_diagnosis_date', sa.DateTime(), nullable=True),
    sa.Column('alk_methods', sa.JSON(), nullable=True),
    sa.Column('alk_fusion_variant', sa.String(length=50), nullable=True),
    sa.Column('tp53_comutation', sa.String(length=20), nullable=True),
    sa.Column('ttf1_expression', sa.String(length=20), nullable=True),
    sa.Column('had_previous_therapy', sa.Boolean(), nullable=True),
    sa.Column('no_previous_therapy', sa.Boolean(), nullable=True),
    sa.Column('previous_therapy_types', sa.JSON(), nullable=True),
    sa.Column('previous_therapy_start_date', sa.DateTime(), nullable=True),
    sa.Column('previous_therapy_end_date', sa.DateTime(), nullable=True),
    sa.Column('previous_therapy_response', sa.String(length=20), nullable=True),
    sa.Column('previous_therapy_stop_reason', sa.Text(), nullable=True),
    sa.Column('alectinib_start_date', sa.DateTime(), nullable=True),
    sa.Column('stage_at_alectinib_start', sa.String(length=50), nullable=True),
    sa.Column('ecog_at_start', sa.Integer(), nullable=True),
    sa.Column('metastases_sites', sa.JSON(), nullable=True),
    sa.Column('metastases_sites_other_text', sa.Text(), nullable=True),
    sa.Column('cns_metastases', sa.Boolean(), nullable=True),
    sa.Column('cns_measurable', sa.String(length=50), nullable=True),
    sa.Column('cns_symptomatic', sa.String(length=50), nullable=True),
    sa.Column('cns_radiotherapy', sa.String(length=100), nullable=True),
    sa.Column('cns_radiotherapy_timing', sa.String(length=50), nullable=True),
    sa.Column('alectinib_therapy_status', sa.String(length=20), nullable=True),
    sa.Column('maximum_response', sa.String(length=20), nullable=True),
    sa.Column('earliest_response_date', sa.DateTime(), nullable=True),
    sa.Column('intracranial_response', sa.String(length=20), nullable=True),
    sa.Column('progression_during_alectinib', sa.String(length=50), nullable=True),
    sa.Column('local_treatment_at_progression', sa.String(length=100), nullable=True),
    sa.Column('progression_sites', sa.JSON(), nullable=True),
    sa.Column('progression_sites_other_text', sa.Text(), nullable=True),
    sa.Column('progression_date', sa.DateTime(), nullable=True),
    sa.Column('continued_after_progression', sa.Boolean(), nullable=True),
    sa.Column('alectinib_end_date', sa.DateTime(), nullable=True),
    sa.Column('alectinib_stop_reason', sa.Text(), nullable=True),
    sa.Column('had_treatment_interruption', sa.Boolean(), nullable=True),
    sa.Column('interruption_reason', sa.Text(), nullable=True),
    sa.Column('interruption_duration_months', sa.Float(), nullable=True),
    sa.Column('had_dose_reduction', sa.Boolean(), nullable=True),
    sa.Column('next_line_treatments', sa.JSON(), nullable=True),
    sa.Column('next_line_start_date', sa.DateTime(), nullable=True),
    sa.Column('progression_on_next_line', sa.Boolean(), nullable=True),
    sa.Column('alectinib_progression_type', sa.String(length=50), nullable=True),
    sa.Column('alectinib_progression_sites', sa.JSON(), nullable=True),
    sa.Column('alectinib_progression_sites_other_text', sa.Text(), nullable=True),
    sa.Column('alectinib_progression_date', sa.DateTime(), nullable=True),
    sa.Column('progression_on_next_line_date', sa.DateTime(), nullable=True),
    sa.Column('next_line_treatments_other_text', sa.Text(), nullable=True),
    sa.Column('next_line_end_date', sa.DateTime(), nullable=True),
    sa.Column('total_lines_after_alectinib', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(), nullable=True),
    sa.Column('age_at_diagnosis', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_clinical_records_id'), 'clinical_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_records_id'), table_name='clinical_records')
    op.drop_table('clinical_records')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_dictionaries_id'), table_name='dictionaries')
    op.drop_index(op.f('ix_dictionaries_category'), table_name='dictionaries')
    op.drop_table('dictionaries')
    # ### end Alembic commands ###
