"""add_parent_field_to_dictionaries

Revision ID: 9ccf6c237d24
Revises: abee23fe8a0f
Create Date: 2025-11-27 13:28:34.781842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ccf6c237d24'
down_revision: Union[str, None] = 'abee23fe8a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionaries', sa.Column('parent', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionaries', 'parent')
    # ### end Alembic commands ###
